sudo: false
language: go
go:
  - "1.8.x"
  - "1.10.x"
  - master
script:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - make clean vendor all install
  - make test-unit
  - make lint
  - make vet
